version: "3.9"
services:
  db:
    container_name: postgres_db
    image: postgres
    ports:
      - "5433:5433"
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}

  app:
    build: .
    command: alembic upgrade head && uvicorn src.main:app --host=${HOST} --port=${PORT} --reload
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env

  redis:
    image: redis
    ports:
      - "6379:6379"
